aula055/notebook/config/routes.rb
Rails.application.routes.draw do

  get '/bemvindo' => 'home#index'
  
  root 'home#index'
  
  resources :phones
  resources :addresses
  resources :contacts #, except: [:edit]
  resources :kinds # cria 8 rotas de forma automática
  

end

aula055/notebook/app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :kind
  has_one :address
  has_many :phones
  
  accepts_nested_attributes_for :address
  accepts_nested_attributes_for :phones, reject_if: :all_blank, allow_destroy: true
  
  validates :name, presence: true, length: { minimum: 3 }
  validates :email, presence: true
end

aula055/notebook/app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]
  before_action :set_options_for_select, only: [:new, :edit, :update, :create]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.order(:name).page(params[:page]).per(15)
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
    @contact.build_address
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  
    def set_options_for_select
      @kind_options_for_select = Kind.all
    end
  
  
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :email, :kind_id, :rmk, 
        address_attributes: [:street, :city, :state],
        phones_attributes: [:id, :phone, :_destroy])
    end
end

aula055/notebook/app/helpers/contacts_helper.rb
module ContactsHelper
end

aula055/notebook/app/views/contacts/_form.html.erb
<%= form_for(@contact, html: { class: "basic-grey" }) do |f| %>
  <h1><%= @contact.model_name.human %></h1>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :kind_id %><br>
    <%= f.collection_select(:kind_id, @kind_options_for_select, :id, :description) %>
  </div>
  
  
  <%= f.fields_for :address do |address_fields| %>
    <div class="field">
      <%= address_fields.label :street %><br>
      <%= address_fields.text_field :street %>
    </div>
    <div class="field">
      <%= address_fields.label :city %><br>
      <%= address_fields.text_field :city %>
    </div>
    <div class="field">
      <%= address_fields.label :state %><br>
      <%= address_fields.select :state, options_for_states(@contact.address.state) %>
    </div>
  <% end %>

  <div id="phones">
    <%= f.fields_for :phones do |phones_fields| %>
      <%= render partial: "phone_fields", locals: { f: phones_fields } %>
    <% end %>
    
    
    <div class="field">
      <%= f.label :phones, ">" %><br>
      <%= link_to_add_association('[Adicionar Telefone]', f, :phones) %>
    </div>
  </div>

  
  <div class="field">
    <%= f.label :rmk %><br>
    <%= f.text_area :rmk %>
  </div>
  <div class="field">
    <%= f.submit t('buttons.save'), class: "button" %>
    <%= link_to t('buttons.back'), contacts_path, class: "button"%>
  </div>
  
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= "#{pluralize(@contact.errors.count, 'error')} #{t('messages.errors')}:" %></h2>

      <ul>
      <% @contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

aula055/notebook/app/views/contacts/_phone_fields.html.erb
<div class="nested-fields">
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone, class: "phone-field" %>
    <%= link_to_remove_association('remover', f)%>
  </div>
</div>

aula055/notebook/app/views/contacts/edit.html.erb
<%= render 'form' %>

aula055/notebook/app/views/contacts/index.html.erb
<div class="basic-grey">
  <p id="notice"><%= notice %></p>
  
  <h1><%= "#{t('messages.listing')} #{@contacts.model.model_name.human(count: @contacts.count)}" %></h1>
  
  <table>
    <thead>
      <tr>
        <th><%= @contacts.model.human_attribute_name("name") %></th>
        <th><%= @contacts.model.human_attribute_name("kind") %></th>
        <th colspan="3"></th>
      </tr>
    </thead>
  
    <tbody>
      <% @contacts.each do |contact| %>
        <tr style="background: <%= cycle('white', '#f0f0f5') %>">
          <td><%= contact.name %></td>
          <td><%= contact.kind.description %></td>
          <td><%= link_to t('buttons.show'), contact %></td>
          <td><%= link_to t('buttons.edit'), edit_contact_path(contact) %></td>
          <td><%= link_to t('buttons.destroy'), contact, method: :delete, data: { confirm: t('messages.confirm') } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  
  <br>
  
  <%= paginate @contacts %>
  
  <br>
  
  <%= link_to t('buttons.new'), new_contact_path %>
</div>

aula055/notebook/app/views/contacts/new.html.erb
<%= render 'form' %>

aula055/notebook/app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contact.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>Kind:</strong>
  <%= @contact.kind %>
</p>

<p>
  <strong>Rmk:</strong>
  <%= @contact.rmk %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>