aula054/notebook/config/routes.rb
Rails.application.routes.draw do

  get '/bemvindo' => 'home#index'
  
  root 'home#index'
  
  resources :phones
  resources :addresses
  resources :contacts #, except: [:edit]
  resources :kinds # cria 8 rotas de forma automática
  

end

aula054/notebook/app/models/kind.rb
class Kind < ActiveRecord::Base
  has_many :contacts
end

aula054/notebook/app/controllers/kinds_controller.rb
class KindsController < ApplicationController
  before_action :set_kind, only: [:show, :edit, :update, :destroy]

  # GET /kinds
  # GET /kinds.json
  def index # nome do arquivo
    @meu_nome = "Jackson Pires"
    @kinds = Kind.all  #  SELECT "kinds".* FROM "kinds"
  end

  # GET /kinds/1
  # GET /kinds/1.json
  def show
  end

  # GET /kinds/new
  def new
    @kind = Kind.new
  end

  # GET /kinds/1/edit
  def edit
  end

  # POST /kinds
  # POST /kinds.json
  def create
    @kind = Kind.new(kind_params)

    respond_to do |format|
      if @kind.save
        format.html { redirect_to @kind, notice: 'Kind was successfully created.' }
        format.json { render :show, status: :created, location: @kind }
      else
        format.html { render :new }
        format.json { render json: @kind.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kinds/1
  # PATCH/PUT /kinds/1.json
  def update
    respond_to do |format|
      if @kind.update(kind_params)
        format.html { redirect_to @kind, notice: 'Kind was successfully updated.' }
        format.json { render :show, status: :ok, location: @kind }
      else
        format.html { render :edit }
        format.json { render json: @kind.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kinds/1
  # DELETE /kinds/1.json
  def destroy
    @kind.destroy
    respond_to do |format|
      format.html { redirect_to kinds_url, notice: 'Kind was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kind
      @kind = Kind.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def kind_params
      params.require(:kind).permit(:description)
    end
end

aula054/notebook/app/helpers/kinds_helper.rb
module KindsHelper
end

aula054/notebook/app/views/kinds/_form.html.erb
<%= form_for(@kind) do |f| %>
  <% if @kind.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@kind.errors.count, "error") %> prohibited this kind from being saved:</h2>

      <ul>
      <% @kind.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

aula054/notebook/app/views/kinds/edit.html.erb
<h1>Editing Kind</h1>

<%= render 'form' %>

<%= link_to 'Show', @kind %> |
<%= link_to 'Back', kinds_path %>

aula054/notebook/app/views/kinds/index.html.erb
<p id="notice"><%= notice %></p>
<% a = 1 + 3  %>
<h1>Listando os Tipos // <%= @meu_nome %> // <%= a %></h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @kinds.each do |kind| %>
      <tr>
        <td><%= kind.description %></td>
        <td><%= link_to 'Show', kind %></td>
        <td><%= link_to 'Edit', edit_kind_path(kind) %></td>
        <td><%= link_to 'Destroy', kind, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Kind', new_kind_path %>

aula054/notebook/app/views/kinds/new.html.erb
<h1>New Kind</h1>

<%= render 'form' %>

<%= link_to 'Back', kinds_path %>

aula054/notebook/app/views/kinds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @kind.description %>
</p>

<%= link_to 'Edit', edit_kind_path(@kind) %> |
<%= link_to 'Back', kinds_path %>